spring.application.name=travelot
server.port=${PORT:8080}
server.servlet.context-path=/travelot

logging.level.org.springframework=info
logging.level.com.web.travelot.mapper=info

# root jdbc:mysql://localhost:3306/travelot?characterEncoding=utf-8 12345
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.MySQL8Dialect

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.web.travelot.po

# redis config
spring.redis.host:localhost
spring.redis.port:6379
spring.cache.type:redis