spring.application.name=travelot
server.port=8080
server.servlet.context-path=/travelot

logging.level.org.springframework=debug
logging.level.com.web.travelot.mapper=debug

spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.url=jdbc:mysql://localhost:3306/elm?characterEncoding=utf-8
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.web.travelot.po